#!/usr/bin/env python3
"""Nexus Orchestrator — Project Generator.

Reads nexus-config.json and produces project-specific scaffolding:
  - docs/agents/TEAM.md
  - docs/agents/SKILL_MAP.md
  - docs/ARCHITECTURE.md (stub)
  - CLAUDE.md (project-specific)
  - .claude/agents/<persona>.md for each persona
  - .claude/hooks/.env with resolved env var values
  - Updates .claude/settings.json env section

Usage:
  python3 generate-project.py --config nexus-config.json --target /path/to/project
  python3 generate-project.py --interactive --target /path/to/project
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from string import Template
from typing import Any


# ── Config schema defaults ────────────────────────────────────────────────────

DEFAULT_CONFIG: dict[str, Any] = {
    "project": {
        "name": "my-project",
        "description": "A project using the Nexus orchestrator system",
        "dev_port": 3000,
        "repo_root_relative": ".",
    },
    "tech_stack": {
        "languages": ["TypeScript"],
        "frontend": "Next.js 15 / TypeScript",
        "backend": "",
        "database": "PostgreSQL",
        "testing": {
            "frontend": ["vitest"],
            "backend": ["pytest"],
        },
    },
    "personas": [
        {
            "name": "forge",
            "role": "Frontend engineer",
            "description": "TypeScript / Next.js implementer",
            "owns": ["app/"],
            "do_not_touch": [],
            "stack_details": ["Next.js 15", "TypeScript"],
            "verification": ["rtk tsc", "rtk lint"],
            "model": "sonnet",
            "effort": "high",
        }
    ],
    "paths": {
        "docs": "docs/",
        "source_roots": ["app/", "src/"],
        "tests": "tests/",
        "agents_doc": "docs/agents/",
    },
    "hooks": {
        "gated_source_paths": "app/,src/,lib/",
        "context_reset_at": 10,
    },
    "skills": {
        "include_generic": True,
        "domain_skills": [],
    },
}


# ── Template strings ──────────────────────────────────────────────────────────

TEAM_MD_TEMPLATE = """\
# Agent Team

Project: **$project_name**

$project_description

## Personas

$persona_table

## Ownership Rules

$ownership_rules

---
*Generated by nexus-orchestrator-template/scripts/generate-project.py*
"""

PERSONA_MD_TEMPLATE = """\
You are **$persona_name_title** ($persona_role) for the **$project_name** project.

## Identity

- **Role:** $persona_role
- **Owns:** $owns_list
- **Do not touch:** $do_not_touch_list

## Stack

$stack_details

## Verification (required before completion)

$verification_cmds

## Output-Dir STRICT (write boundary)

**You MAY write to:**
$owns_write

**You MUST NOT write to:**
$forbidden_write

## Completion markers (required as H2)

- `## NEXUS:DONE` — code shipped + verified
- `## NEXUS:BLOCKED` — cannot ship
- `## NEXUS:NEEDS-DECISION` — design ambiguity
- `## NEXUS:CHECKPOINT` — partial progress
- `## NEXUS:REVISE` — only in response to Lens

## Standards

- Full type hints on every function.
- Read before edit. Re-read after any other tool changes a file.
- Respect `do_not_touch`; escalate via `## NEXUS:NEEDS-DECISION` if a needed change is forbidden.
"""

SKILL_MAP_MD_TEMPLATE = """\
# Skill Map

Maps personas to required skills. Used by `skills-required-guard.sh` to enforce
that code-writing briefs declare their skill dependencies.

## Persona Skills

$persona_skill_rows

---
*Generated by nexus-orchestrator-template/scripts/generate-project.py*
"""

CLAUDE_MD_TEMPLATE = """\
# $project_name — Agent Directives

## Nexus Protocol

The Nexus orchestrator is configured in `.claude/settings.json`. Deep protocol
detail lives in the **`nexus-protocol`** skill.

## Source of Truth Precedence

1. `.memory/project.db` — live decisions, tasks, sessions
2. `docs/CONSTITUTION.md` — governance articles
3. `docs/` — DECISIONS.md, TASKS.md, PRD.md, ARCHITECTURE.md, features/*
4. Nested `CLAUDE.md` files

## Stack

$stack_summary

## Dev Port

$dev_port — never change this

## Rules

- Delegate per `$agents_doc_path/TEAM.md` — Nexus does not write code itself.
- Before any new feature: spec + GWT + planning gate PASS.
- Verification before done: $verification_summary

## Feature Specs

Index in `docs/TASKS.md`. Active specs under `docs/features/FEAT-*.md`.
"""

ARCHITECTURE_MD_TEMPLATE = """\
# Architecture

## Overview

$project_description

## Tech Stack

$stack_summary

## Source Tree

$source_tree

## Personas

$persona_list

---
*Stub generated by nexus-orchestrator-template. Fill in with real architecture details.*
"""


# ── Helpers ───────────────────────────────────────────────────────────────────

def deep_merge(base: dict[str, Any], override: dict[str, Any]) -> dict[str, Any]:
    """Recursively merge override into base (override wins on conflicts)."""
    result = dict(base)
    for key, val in override.items():
        if key in result and isinstance(result[key], dict) and isinstance(val, dict):
            result[key] = deep_merge(result[key], val)
        else:
            result[key] = val
    return result


def load_config(config_path: str) -> dict[str, Any]:
    with open(config_path, encoding="utf-8") as fh:
        user_cfg = json.load(fh)
    return deep_merge(DEFAULT_CONFIG, user_cfg)


def prompt(label: str, default: str) -> str:
    val = input(f"{label} [{default}]: ").strip()
    return val if val else default


def interactive_config() -> dict[str, Any]:
    """Prompt user for key config values and return a config dict."""
    print("\nNexus Orchestrator — Interactive Setup\n")
    cfg: dict[str, Any] = deep_merge(DEFAULT_CONFIG, {})

    cfg["project"]["name"] = prompt("Project name", cfg["project"]["name"])
    cfg["project"]["description"] = prompt(
        "Project description", cfg["project"]["description"]
    )
    cfg["project"]["dev_port"] = int(
        prompt("Dev port", str(cfg["project"]["dev_port"]))
    )

    languages_raw = prompt(
        "Languages (comma-separated)", ",".join(cfg["tech_stack"]["languages"])
    )
    cfg["tech_stack"]["languages"] = [lang.strip() for lang in languages_raw.split(",")]

    cfg["tech_stack"]["frontend"] = prompt(
        "Frontend stack", cfg["tech_stack"]["frontend"]
    )
    cfg["tech_stack"]["backend"] = prompt(
        "Backend stack", cfg["tech_stack"]["backend"]
    )
    cfg["tech_stack"]["database"] = prompt(
        "Database", cfg["tech_stack"]["database"]
    )

    source_roots_raw = prompt(
        "Source roots (comma-separated)", ",".join(cfg["paths"]["source_roots"])
    )
    cfg["paths"]["source_roots"] = [r.strip() for r in source_roots_raw.split(",")]

    gated = prompt(
        "Gated source paths for lens-gate (comma-separated)",
        cfg["hooks"]["gated_source_paths"],
    )
    cfg["hooks"]["gated_source_paths"] = gated

    print("\nUsing default personas (forge). Edit nexus-config.json to customize.\n")
    return cfg


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def write_file(path: Path, content: str) -> None:
    ensure_dir(path.parent)
    path.write_text(content, encoding="utf-8")
    print(f"   wrote {path}")


# ── Generators ────────────────────────────────────────────────────────────────

def generate_team_md(cfg: dict[str, Any], target: Path) -> None:
    personas = cfg["personas"]
    agents_doc = cfg["paths"]["agents_doc"].rstrip("/")

    rows = ["| Persona | Role | Owns |", "|---------|------|------|"]
    for p in personas:
        owns = ", ".join(f"`{o}`" for o in p["owns"])
        rows.append(f"| **{p['name']}** | {p['role']} | {owns} |")

    ownership_lines: list[str] = []
    for p in personas:
        owns = ", ".join(f"`{o}`" for o in p["owns"])
        dnt = ", ".join(f"`{d}`" for d in p.get("do_not_touch", []))
        line = f"- **{p['name']}** owns {owns}"
        if dnt:
            line += f"; must not touch {dnt}"
        ownership_lines.append(line)

    content = Template(TEAM_MD_TEMPLATE).substitute(
        project_name=cfg["project"]["name"],
        project_description=cfg["project"]["description"],
        persona_table="\n".join(rows),
        ownership_rules="\n".join(ownership_lines),
    )
    write_file(target / agents_doc / "TEAM.md", content)


def generate_skill_map(cfg: dict[str, Any], target: Path) -> None:
    personas = cfg["personas"]
    agents_doc = cfg["paths"]["agents_doc"].rstrip("/")
    generic_skills = cfg["skills"].get("include_generic", True)
    domain_skills = cfg["skills"].get("domain_skills", [])

    rows: list[str] = []
    for p in personas:
        skills: list[str] = []
        if generic_skills:
            skills += ["tdd-patterns", "verification-protocols"]
        skills += domain_skills
        # Heuristic: add stack-specific skills
        for lang in cfg["tech_stack"].get("languages", []):
            if "TypeScript" in lang:
                skills += ["forge-ui-conventions", "vitest-rtl-idioms"]
            if "Python" in lang:
                skills += ["pipeline-data-conventions", "pytest-idioms"]
        skills = list(dict.fromkeys(skills))  # dedupe, preserve order
        rows.append(f"| `{p['name']}` | {', '.join(f'`{s}`' for s in skills)} |")

    header = ["| Persona | Required Skills |", "|---------|----------------|"]
    content = Template(SKILL_MAP_MD_TEMPLATE).substitute(
        persona_skill_rows="\n".join(header + rows),
    )
    write_file(target / agents_doc / "SKILL_MAP.md", content)


def generate_persona_agents(cfg: dict[str, Any], target: Path) -> None:
    agents_dir = target / ".claude" / "agents"
    ensure_dir(agents_dir)

    for p in cfg["personas"]:
        owns_write = "\n".join(f"- `{o}**`" for o in p["owns"])
        all_dirs = {o for pp in cfg["personas"] for o in pp["owns"]}
        forbidden = sorted(all_dirs - set(p["owns"]))
        forbidden += p.get("do_not_touch", [])
        forbidden_write = "\n".join(f"- `{d}**`" for d in forbidden) or "- (none extra)"

        stack = p.get("stack_details", cfg["tech_stack"].get("languages", []))
        stack_md = "\n".join(f"- {s}" for s in stack)

        verification = p.get("verification", ["rtk tsc", "rtk lint"])
        verification_md = "\n".join(f"```bash\n{v}\n```" for v in verification)

        owns_list = ", ".join(f"`{o}`" for o in p["owns"])
        dnt_list = ", ".join(f"`{d}`" for d in p.get("do_not_touch", [])) or "nothing extra"

        content = Template(PERSONA_MD_TEMPLATE).substitute(
            persona_name_title=p["name"].capitalize(),
            persona_role=p["role"],
            project_name=cfg["project"]["name"],
            owns_list=owns_list,
            do_not_touch_list=dnt_list,
            stack_details=stack_md,
            verification_cmds=verification_md,
            owns_write=owns_write,
            forbidden_write=forbidden_write,
        )
        write_file(agents_dir / f"{p['name']}.md", content)


def generate_claude_md(cfg: dict[str, Any], target: Path) -> None:
    tech = cfg["tech_stack"]
    parts: list[str] = []
    if tech.get("frontend"):
        parts.append(f"- **Frontend:** {tech['frontend']}")
    if tech.get("backend"):
        parts.append(f"- **Backend:** {tech['backend']}")
    if tech.get("database"):
        parts.append(f"- **Database:** {tech['database']}")
    stack_summary = "\n".join(parts) if parts else "- (configure in nexus-config.json)"

    personas = cfg["personas"]
    verifications = sorted({v for p in personas for v in p.get("verification", [])})
    verification_summary = " + ".join(f"`{v}`" for v in verifications) if verifications else "`rtk tsc` + `rtk lint`"

    content = Template(CLAUDE_MD_TEMPLATE).substitute(
        project_name=cfg["project"]["name"],
        stack_summary=stack_summary,
        dev_port=cfg["project"]["dev_port"],
        agents_doc_path=cfg["paths"]["agents_doc"].rstrip("/"),
        verification_summary=verification_summary,
    )
    # Only write if not already present (don't overwrite user-edited CLAUDE.md)
    dest = target / "CLAUDE.md"
    if dest.exists():
        print("   skipped CLAUDE.md (already exists — review manually)")
    else:
        write_file(dest, content)


def generate_architecture_md(cfg: dict[str, Any], target: Path) -> None:
    tech = cfg["tech_stack"]
    stack_lines: list[str] = []
    if tech.get("languages"):
        stack_lines.append(f"- Languages: {', '.join(tech['languages'])}")
    if tech.get("frontend"):
        stack_lines.append(f"- Frontend: {tech['frontend']}")
    if tech.get("backend"):
        stack_lines.append(f"- Backend: {tech['backend']}")
    if tech.get("database"):
        stack_lines.append(f"- Database: {tech['database']}")
    stack_summary = "\n".join(stack_lines)

    source_roots = cfg["paths"].get("source_roots", ["src/"])
    source_tree = "\n".join(f"- `{r}`" for r in source_roots)

    persona_list = "\n".join(
        f"- **{p['name']}** — {p['role']}" for p in cfg["personas"]
    )

    content = Template(ARCHITECTURE_MD_TEMPLATE).substitute(
        project_description=cfg["project"]["description"],
        stack_summary=stack_summary,
        source_tree=source_tree,
        persona_list=persona_list,
    )
    dest = target / "docs" / "ARCHITECTURE.md"
    if dest.exists():
        print("   skipped docs/ARCHITECTURE.md (already exists)")
    else:
        write_file(dest, content)


def generate_hooks_env(cfg: dict[str, Any], target: Path) -> None:
    hooks_cfg = cfg["hooks"]
    project_name = cfg["project"]["name"]
    gated = hooks_cfg.get("gated_source_paths", "app/,src/,lib/")
    context_reset_at = hooks_cfg.get("context_reset_at", 10)

    content = f"""\
# Nexus Hook Environment Variables — {project_name}
# Auto-generated by generate-project.py. Customize as needed.
export REPO_ROOT="${{REPO_ROOT:-$(pwd)}}"
export DB_PATH="${{DB_PATH:-$(pwd)/.memory/project.db}}"
export GATED_SOURCE_PATHS="${{GATED_SOURCE_PATHS:-{gated}}}"
export CONTEXT_RESET_AT="${{CONTEXT_RESET_AT:-{context_reset_at}}}"
export SKILL_MAP_PATH="${{SKILL_MAP_PATH:-docs/agents/SKILL_MAP.md}}"
export NEXUS_PROJECT_NAME="${{NEXUS_PROJECT_NAME:-{project_name}}}"
"""
    env_path = target / ".claude" / "hooks" / ".env"
    if env_path.exists():
        print("   skipped .claude/hooks/.env (already exists — review manually)")
    else:
        write_file(env_path, content)


def update_settings_json(cfg: dict[str, Any], target: Path) -> None:
    settings_path = target / ".claude" / "settings.json"
    if not settings_path.exists():
        print("   skipped .claude/settings.json update (file not found)")
        return

    with open(settings_path, encoding="utf-8") as fh:
        try:
            settings = json.load(fh)
        except json.JSONDecodeError as exc:
            print(f"   WARNING: cannot parse settings.json: {exc}")
            return

    env = settings.setdefault("env", {})
    env["NEXUS_PROJECT_NAME"] = cfg["project"]["name"]
    env["MEMORY_TOOL_PATH"] = ".memory/files"

    with open(settings_path, "w", encoding="utf-8") as fh:
        json.dump(settings, fh, indent=2)
        fh.write("\n")
    print("   updated .claude/settings.json env section")


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Nexus Orchestrator — Project Generator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--config",
        metavar="FILE",
        help="Path to nexus-config.json",
    )
    parser.add_argument(
        "--interactive",
        action="store_true",
        help="Prompt for key config values interactively",
    )
    parser.add_argument(
        "--target",
        metavar="DIR",
        default=".",
        help="Target project directory (default: current directory)",
    )
    args = parser.parse_args()

    target = Path(args.target).resolve()
    if not target.is_dir():
        print(f"ERROR: Target directory not found: {target}", file=sys.stderr)
        sys.exit(1)

    if args.interactive:
        cfg = interactive_config()
    elif args.config:
        cfg = load_config(args.config)
    else:
        # Try to find config in target or cwd
        for candidate in [target / "nexus-config.json", Path("nexus-config.json")]:
            if candidate.exists():
                cfg = load_config(str(candidate))
                print(f"   Using config: {candidate}")
                break
        else:
            print("No config file found. Running in interactive mode.")
            cfg = interactive_config()

    print(f"\nGenerating project: {cfg['project']['name']}")
    print(f"Target: {target}\n")

    generate_team_md(cfg, target)
    generate_skill_map(cfg, target)
    generate_persona_agents(cfg, target)
    generate_claude_md(cfg, target)
    generate_architecture_md(cfg, target)
    generate_hooks_env(cfg, target)
    update_settings_json(cfg, target)

    print("\nGeneration complete.")
    print("Review generated files and customize as needed.")


if __name__ == "__main__":
    main()
